export const PROFILES = {
    STUDENT: "STUDENT",
    DRIVER: "DRIVER",
    ADMIN: "ADMIN",
    ORGANIZATION: "ORGANIZATION",
}

export const STUDENT_STATUS = {
    ONBOARDED: "ONBOARDED",
    INPROGRESS: "INPROGRESS",
    COMPLETED: "COMPLETED",
}

export const ATTENDANCE_STATUS = {
    STARTED: "STARTED",
    COMPLETED: "COMPLETED",
}

export const ORGANIZATION_JOINED_FROM = {
    SIGNUP_PAGE: "SIGNUP_PAGE",
    ADMIN_DASHBOARD: "ADMIN_DASHBOARD",
}